version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_USER: webapp
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./initialize.sql:/docker-entrypoint-initdb.d/10-init.sql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
      
  api:
    image: pa-backend
    container_name: api
    restart: always
    environment:
      MYSQL_USER: webapp
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: db
      DB_HOST: db
    ports:
      - 5001:5001
      
  simulation:
    image: pa-simulation
    container_name: simulation
    restart: always
    environment:
      MYSQL_USER: webapp
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: db
      DB_HOST: db
  
  ui:
    image: pa-ui
    container_name: front
    restart: always
    environment:
      MYSQL_USER: webapp
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: db
      DB_HOST: db
    ports:
      - 80:3000